export type LocaleCode = 'es' | 'pt' | 'de' | 'fr' | 'ru' | 'ja' | 'zh' | 'it' | 'ar' | 'hi';

export interface LocalizedHomeContent {
  code: LocaleCode;
  languageName: string;
  lang: string;
  dir: 'ltr' | 'rtl';
  ogLocale: string;
  title: string;
  description: string;
  keywords: string;
  badge: string;
  h1: string;
  intro: string;
  calculatorTitle: string;
  calculateLabel: string;
  resultLabel: string;
  metricLabel: string;
  imperialLabel: string;
  clearLabel: string;
  copyLabel: string;
  guideTitle: string;
  sections: { heading: string; paragraphs: string[] }[];
  faqTitle: string;
  faqs: { question: string; answer: string }[];
  shapeNames: Record<'box' | 'cylinder' | 'sphere' | 'cube' | 'cone', string>;
}

export const ENGLISH_HOME = 'https://thevolumecalculator.com/';

export const LOCALIZED_HOMES: Record<LocaleCode, LocalizedHomeContent> = {
  es: {
    code: 'es', languageName: 'Español', lang: 'es', dir: 'ltr', ogLocale: 'es_ES',
    title: 'Calculadora de volumen online: litros, m³ y galones',
    description: 'Calculadora de volumen gratuita para cilindros, esferas, cubos, conos y prismas. Resultados instantáneos en litros, metros cúbicos, pies cúbicos y galones.',
    keywords: 'calculadora de volumen, calcular volumen cilindro, volumen de un prisma, volumen de una esfera, calculadora de cbm, calcular litros piscina',
    badge: 'Cálculos rápidos y gratuitos', h1: 'Calculadora de volumen online',
    intro: 'Calcula el volumen y la capacidad de cajas, cilindros, esferas, cubos y conos. Introduce las medidas, elige el sistema métrico o imperial y obtén resultados inmediatos con la fórmula aplicada paso a paso.',
    calculatorTitle: 'Calculadora interactiva', calculateLabel: 'Introduce las medidas', resultLabel: 'Volumen calculado', metricLabel: 'Métrico', imperialLabel: 'Imperial', clearLabel: 'Borrar', copyLabel: 'Copiar', guideTitle: 'Cómo calcular el volumen',
    sections: [
      { heading: 'Qué es el volumen y cómo se calcula', paragraphs: ['El volumen mide el espacio tridimensional que ocupa un objeto o la capacidad interior de un recipiente. Se expresa en unidades cúbicas, como centímetros cúbicos (cm³), metros cúbicos (m³) o pies cúbicos (ft³), y también en unidades de capacidad como litros y galones.', 'Para calcularlo, identifica la forma, mide sus dimensiones y aplica la fórmula correcta. Un prisma rectangular usa V = largo × ancho × alto; un cilindro usa V = πr²h; una esfera usa V = ⁴⁄₃πr³. La herramienta convierte automáticamente unidades mixtas.'] },
      { heading: 'Litros, metros cúbicos y aplicaciones', paragraphs: ['En países métricos, 1 m³ equivale exactamente a 1.000 litros. Esto resulta útil para calcular agua de piscinas, depósitos, acuarios y cajas de transporte. Para una piscina rectangular se multiplica largo × ancho × profundidad media y después se convierte el resultado a litros.', 'La calculadora también sirve para calcular CBM en transporte: mide la caja en metros y multiplica las tres dimensiones. Para resultados fiables, utiliza medidas interiores al calcular capacidad y medidas exteriores al estimar espacio de carga.'] },
    ], faqTitle: 'Preguntas frecuentes',
    faqs: [{ question: '¿Cómo calcular el volumen de un cilindro?', answer: 'Multiplica π por el radio al cuadrado y por la altura: V = πr²h. Todas las medidas deben representar la misma unidad física.' }, { question: '¿Cuántos litros hay en un metro cúbico?', answer: 'Un metro cúbico equivale exactamente a 1.000 litros.' }],
    shapeNames: { box: 'Prisma rectangular', cylinder: 'Cilindro', sphere: 'Esfera', cube: 'Cubo', cone: 'Cono' },
  },
  pt: {
    code: 'pt', languageName: 'Português', lang: 'pt-BR', dir: 'ltr', ogLocale: 'pt_BR',
    title: 'Calculadora de volume: litros, m³ e galões', description: 'Calculadora de volume gratuita para cilindro, esfera, cubo, cone e caixa. Converta para litros, metros cúbicos, pés cúbicos e galões.',
    keywords: "calculadora de volume, calcular volume cilindro, volume da esfera, volume de caixa d'água, calcular litros de piscina, calcular cbm frete",
    badge: 'Cálculos rápidos e gratuitos', h1: 'Calculadora de volume online', intro: 'Calcule o volume de caixas, cilindros, esferas, cubos e cones. Informe as medidas, escolha o sistema métrico ou imperial e veja o resultado com conversões instantâneas.',
    calculatorTitle: 'Calculadora interativa', calculateLabel: 'Informe as medidas', resultLabel: 'Volume calculado', metricLabel: 'Métrico', imperialLabel: 'Imperial', clearLabel: 'Limpar', copyLabel: 'Copiar', guideTitle: 'Como calcular volume',
    sections: [{ heading: 'O que é volume?', paragraphs: ['Volume é a quantidade de espaço tridimensional ocupada por um objeto ou disponível dentro de um recipiente. As unidades mais usadas são cm³, m³, litros, pés cúbicos e galões.', 'A fórmula depende da forma. Para uma caixa, use comprimento × largura × altura. Para um cilindro, use V = πr²h. Para uma esfera, use V = ⁴⁄₃πr³.'] }, { heading: 'Piscinas, caixas d’água e frete CBM', paragraphs: ['Um metro cúbico corresponde exatamente a 1.000 litros. Essa relação facilita o cálculo de piscinas e caixas d’água. Em piscinas com fundo inclinado, use a média entre a profundidade rasa e a profunda.', 'No transporte, CBM significa metro cúbico. Multiplique comprimento, largura e altura em metros para saber o espaço ocupado pela carga.'] }],
    faqTitle: 'Perguntas frequentes', faqs: [{ question: 'Como calcular o volume de um cilindro?', answer: 'Use V = πr²h: multiplique pi pelo raio ao quadrado e pela altura.' }, { question: 'Quantos litros existem em 1 m³?', answer: 'Um metro cúbico contém exatamente 1.000 litros.' }], shapeNames: { box: 'Caixa retangular', cylinder: 'Cilindro', sphere: 'Esfera', cube: 'Cubo', cone: 'Cone' },
  },
  de: {
    code: 'de', languageName: 'Deutsch', lang: 'de', dir: 'ltr', ogLocale: 'de_DE', title: 'Volumenrechner – Volumen in Liter und m³ berechnen', description: 'Kostenloser Volumenrechner für Quader, Zylinder, Kugel, Würfel und Kegel. Ergebnisse in Litern, Kubikmetern, Kubikfuß und Gallonen.', keywords: 'Volumenrechner, Volumen berechnen, Zylinder Volumen berechnen, Pool Volumen Rechner, Quader Volumen Rechner, Kugel Volumen, Liter Rechner', badge: 'Schnell und kostenlos', h1: 'Online-Volumenrechner', intro: 'Berechnen Sie Volumen und Fassungsvermögen von Quadern, Zylindern, Kugeln, Würfeln und Kegeln. Wählen Sie metrische oder imperiale Einheiten und erhalten Sie sofort umgerechnete Ergebnisse.', calculatorTitle: 'Interaktiver Rechner', calculateLabel: 'Maße eingeben', resultLabel: 'Berechnetes Volumen', metricLabel: 'Metrisch', imperialLabel: 'Imperial', clearLabel: 'Löschen', copyLabel: 'Kopieren', guideTitle: 'Volumen richtig berechnen', sections: [{ heading: 'Was ist Volumen?', paragraphs: ['Das Volumen beschreibt den dreidimensionalen Rauminhalt eines Körpers oder das Fassungsvermögen eines Behälters. Es wird in Kubikzentimetern, Kubikmetern, Litern oder Kubikfuß angegeben.', 'Für einen Quader gilt V = Länge × Breite × Höhe. Ein Zylinder wird mit V = πr²h berechnet, eine Kugel mit V = ⁴⁄₃πr³. Der Rechner übernimmt die Einheitenumrechnung.'] }, { heading: 'Liter, Kubikmeter und Poolvolumen', paragraphs: ['Ein Kubikmeter entspricht genau 1.000 Litern. Für Pools mit flachem Boden multiplizieren Sie Länge, Breite und Wassertiefe. Bei einem Gefälle verwenden Sie die mittlere Tiefe.', 'Messen Sie für das Fassungsvermögen die Innenmaße. Für Versand- oder Lagerplatz sind dagegen die Außenmaße maßgeblich.'] }], faqTitle: 'Häufige Fragen', faqs: [{ question: 'Wie berechnet man das Volumen eines Zylinders?', answer: 'Mit V = πr²h. Radius quadrieren, mit π und anschließend mit der Höhe multiplizieren.' }, { question: 'Wie viele Liter sind ein Kubikmeter?', answer: 'Ein Kubikmeter entspricht genau 1.000 Litern.' }], shapeNames: { box: 'Quader', cylinder: 'Zylinder', sphere: 'Kugel', cube: 'Würfel', cone: 'Kegel' },
  },
  fr: {
    code: 'fr', languageName: 'Français', lang: 'fr', dir: 'ltr', ogLocale: 'fr_FR', title: 'Calculateur de volume – litres, m³ et gallons', description: 'Calculateur de volume gratuit pour cylindre, sphère, cube, cône et pavé droit. Conversion en litres, mètres cubes, pieds cubes et gallons.', keywords: 'calculateur de volume, calcul du volume, calcul volume cylindre, calculer volume piscine, calcul m3, volume sphere, calculateur cbm', badge: 'Calcul rapide et gratuit', h1: 'Calculateur de volume en ligne', intro: 'Calculez le volume et la capacité d’une boîte, d’un cylindre, d’une sphère, d’un cube ou d’un cône. Choisissez les unités métriques ou impériales et obtenez une conversion instantanée.', calculatorTitle: 'Calculateur interactif', calculateLabel: 'Saisissez les dimensions', resultLabel: 'Volume calculé', metricLabel: 'Métrique', imperialLabel: 'Impérial', clearLabel: 'Effacer', copyLabel: 'Copier', guideTitle: 'Comment calculer un volume', sections: [{ heading: 'Définition et formules du volume', paragraphs: ['Le volume mesure l’espace à trois dimensions occupé par un objet ou contenu dans un récipient. Il s’exprime en cm³, m³, litres, pieds cubes ou gallons.', 'Un pavé droit utilise V = longueur × largeur × hauteur. Pour un cylindre, V = πr²h. Pour une sphère, V = ⁴⁄₃πr³. Le calculateur accepte des unités différentes pour chaque dimension.'] }, { heading: 'Calcul en m³, litres et volume de piscine', paragraphs: ['Un mètre cube équivaut exactement à 1 000 litres. Pour une piscine rectangulaire, multipliez la longueur par la largeur et la profondeur moyenne, puis convertissez le résultat en litres.', 'Utilisez les dimensions intérieures pour calculer une capacité réelle et les dimensions extérieures pour calculer l’encombrement d’un colis ou d’un chargement.'] }], faqTitle: 'Questions fréquentes', faqs: [{ question: 'Comment calculer le volume d’un cylindre ?', answer: 'Appliquez V = πr²h : multipliez π par le carré du rayon puis par la hauteur.' }, { question: 'Combien de litres contient 1 m³ ?', answer: 'Un mètre cube contient exactement 1 000 litres.' }], shapeNames: { box: 'Pavé droit', cylinder: 'Cylindre', sphere: 'Sphère', cube: 'Cube', cone: 'Cône' },
  },
  ru: {
    code: 'ru', languageName: 'Русский', lang: 'ru', dir: 'ltr', ogLocale: 'ru_RU', title: 'Калькулятор объема — литры, м³ и галлоны', description: 'Бесплатный калькулятор объема цилиндра, шара, куба, конуса и прямоугольного параллелепипеда. Перевод в литры и кубические метры.', keywords: 'калькулятор объема, объем цилиндра калькулятор, расчет объема куба, калькулятор объема бассейна, калькулятор кубических метров', badge: 'Быстрый бесплатный расчет', h1: 'Онлайн-калькулятор объема', intro: 'Рассчитайте объем коробки, цилиндра, шара, куба или конуса. Выберите метрические либо имперские единицы и получите мгновенный результат с преобразованием единиц.', calculatorTitle: 'Интерактивный калькулятор', calculateLabel: 'Введите размеры', resultLabel: 'Рассчитанный объем', metricLabel: 'Метрические', imperialLabel: 'Имперские', clearLabel: 'Очистить', copyLabel: 'Копировать', guideTitle: 'Как рассчитать объем', sections: [{ heading: 'Что такое объем?', paragraphs: ['Объем показывает, сколько трехмерного пространства занимает тело или сколько вещества помещается в сосуд. Основные единицы — см³, м³, литры, кубические футы и галлоны.', 'Для прямоугольного параллелепипеда используется V = длина × ширина × высота. Для цилиндра — V = πr²h, для шара — V = ⁴⁄₃πr³.'] }, { heading: 'Кубические метры, литры и бассейны', paragraphs: ['Один кубический метр равен точно 1 000 литров. Объем прямоугольного бассейна находят умножением длины, ширины и средней глубины.', 'Для вместимости измеряйте внутренние размеры, а для места, занимаемого грузом, — внешние. Все линейные размеры перед умножением должны быть приведены к совместимым единицам.'] }], faqTitle: 'Частые вопросы', faqs: [{ question: 'Как рассчитать объем цилиндра?', answer: 'Используйте формулу V = πr²h: квадрат радиуса умножьте на π и высоту.' }, { question: 'Сколько литров в одном м³?', answer: 'В одном кубическом метре ровно 1 000 литров.' }], shapeNames: { box: 'Параллелепипед', cylinder: 'Цилиндр', sphere: 'Шар', cube: 'Куб', cone: 'Конус' },
  },
  ja: {
    code: 'ja', languageName: '日本語', lang: 'ja', dir: 'ltr', ogLocale: 'ja_JP', title: '体積計算機｜リットル・立方メートルを自動計算', description: '円柱、球、立方体、円すい、直方体の無料体積計算機。cm・m・リットル・m³・立方フィートにすぐ変換できます。', keywords: '体積 計算, 体積 計算機, 円柱 体積 計算, 球の体積 計算, 立方体 体積, 容積 計算', badge: '無料ですぐに計算', h1: 'オンライン体積計算機', intro: '直方体、円柱、球、立方体、円すいの体積と容積を計算します。寸法を入力し、メートル法またはヤード・ポンド法を選ぶと、結果をすぐに換算できます。', calculatorTitle: '体積を計算', calculateLabel: '寸法を入力', resultLabel: '計算した体積', metricLabel: 'メートル法', imperialLabel: 'ヤード・ポンド法', clearLabel: 'クリア', copyLabel: 'コピー', guideTitle: '体積の求め方', sections: [{ heading: '体積とは', paragraphs: ['体積は、物体が占める三次元の空間や容器に入る量を表します。単位には cm³、m³、リットル、立方フィートなどがあります。', '直方体は V = 長さ × 幅 × 高さ、円柱は V = πr²h、球は V = ⁴⁄₃πr³で求めます。計算機は入力単位を自動で換算します。'] }, { heading: 'リットル・m³・容積の換算', paragraphs: ['1 m³ は正確に 1,000 リットルです。水槽やプールでは、内側の寸法を使うと実際の容量を計算できます。', '梱包や輸送に必要な空間を求める場合は外寸を使用します。測定値の精度が結果の精度を決めるため、同じ基準で測ってください。'] }], faqTitle: 'よくある質問', faqs: [{ question: '円柱の体積はどう求めますか？', answer: 'V = πr²h を使います。半径の二乗に円周率と高さを掛けます。' }, { question: '1 m³ は何リットルですか？', answer: '1 立方メートルは正確に 1,000 リットルです。' }], shapeNames: { box: '直方体', cylinder: '円柱', sphere: '球', cube: '立方体', cone: '円すい' },
  },
  zh: {
    code: 'zh', languageName: '中文', lang: 'zh-Hans', dir: 'ltr', ogLocale: 'zh_CN', title: '体积计算器｜升、立方米与立方英尺换算', description: '免费体积计算器，可计算长方体、圆柱、球体、立方体和圆锥体积，并换算升、立方米、立方英尺和加仑。', keywords: '体积计算器, 圆柱体积计算, 球体体积计算, 立方米计算器, 集装箱装柜计算', badge: '免费快速计算', h1: '在线体积计算器', intro: '计算长方体、圆柱、球体、立方体和圆锥的体积或容积。输入尺寸并选择公制或英制，即可获得实时结果和单位换算。', calculatorTitle: '交互式计算器', calculateLabel: '输入尺寸', resultLabel: '计算体积', metricLabel: '公制', imperialLabel: '英制', clearLabel: '清除', copyLabel: '复制', guideTitle: '如何计算体积', sections: [{ heading: '体积的定义与公式', paragraphs: ['体积表示物体占据的三维空间，或容器内部能够容纳的容量。常用单位包括立方厘米、立方米、升、立方英尺和加仑。', '长方体公式为 V = 长 × 宽 × 高；圆柱公式为 V = πr²h；球体公式为 V = ⁴⁄₃πr³。计算器会自动处理单位换算。'] }, { heading: '立方米、升与装柜 CBM', paragraphs: ['1 立方米等于 1,000 升。计算水箱或泳池容量时应使用内部尺寸；计算货物占用空间时应使用外部尺寸。', '国际货运中的 CBM 指立方米。将以米为单位的长、宽、高相乘，即可得到货物体积和集装箱装柜所需空间。'] }], faqTitle: '常见问题', faqs: [{ question: '圆柱体积怎样计算？', answer: '使用 V = πr²h，即半径平方乘以圆周率和高度。' }, { question: '1 立方米等于多少升？', answer: '1 立方米准确等于 1,000 升。' }], shapeNames: { box: '长方体', cylinder: '圆柱', sphere: '球体', cube: '立方体', cone: '圆锥' },
  },
  it: {
    code: 'it', languageName: 'Italiano', lang: 'it', dir: 'ltr', ogLocale: 'it_IT', title: 'Calcolatore di volume: litri, m³ e galloni', description: 'Calcolatore di volume gratuito per cilindro, sfera, cubo, cono e parallelepipedo. Conversione immediata in litri, metri cubi e piedi cubi.', keywords: 'calcolatore di volume, calcolo volume, calcolo volume cilindro, volume sfera calcolo, calcolo metri cubi, calcolo volume piscina litri', badge: 'Calcolo rapido e gratuito', h1: 'Calcolatore di volume online', intro: 'Calcola il volume e la capacità di scatole, cilindri, sfere, cubi e coni. Inserisci le misure, scegli il sistema metrico o imperiale e ottieni conversioni immediate.', calculatorTitle: 'Calcolatore interattivo', calculateLabel: 'Inserisci le misure', resultLabel: 'Volume calcolato', metricLabel: 'Metrico', imperialLabel: 'Imperiale', clearLabel: 'Cancella', copyLabel: 'Copia', guideTitle: 'Come calcolare il volume', sections: [{ heading: 'Definizione e formule del volume', paragraphs: ['Il volume misura lo spazio tridimensionale occupato da un oggetto o la capacità interna di un contenitore. Si esprime in cm³, m³, litri, piedi cubi o galloni.', 'Per un parallelepipedo usa V = lunghezza × larghezza × altezza. Per un cilindro usa V = πr²h; per una sfera V = ⁴⁄₃πr³.'] }, { heading: 'Metri cubi, litri e piscine', paragraphs: ['Un metro cubo equivale esattamente a 1.000 litri. Per una piscina rettangolare moltiplica lunghezza, larghezza e profondità media.', 'Usa le misure interne per conoscere la capacità reale di un serbatoio e quelle esterne per stimare lo spazio occupato da un pacco o da un carico.'] }], faqTitle: 'Domande frequenti', faqs: [{ question: 'Come si calcola il volume di un cilindro?', answer: 'Usa V = πr²h: moltiplica il quadrato del raggio per π e per l’altezza.' }, { question: 'Quanti litri contiene un metro cubo?', answer: 'Un metro cubo contiene esattamente 1.000 litri.' }], shapeNames: { box: 'Parallelepipedo', cylinder: 'Cilindro', sphere: 'Sfera', cube: 'Cubo', cone: 'Cono' },
  },
  ar: {
    code: 'ar', languageName: 'العربية', lang: 'ar', dir: 'rtl', ogLocale: 'ar_SA', title: 'حاسبة الحجم — اللترات والأمتار المكعبة والجالونات', description: 'حاسبة حجم مجانية للأسطوانة والكرة والمكعب والمخروط ومتوازي المستطيلات، مع التحويل إلى اللترات والأمتار المكعبة والقدم المكعبة.', keywords: 'حاسبة الحجم, حساب الحجم, حساب حجم الاسطوانة, حساب حجم الخزان, حساب حجم المسبح, حساب الامتار المكعبة', badge: 'حساب سريع ومجاني', h1: 'حاسبة الحجم عبر الإنترنت', intro: 'احسب حجم وسعة الصناديق والأسطوانات والكرات والمكعبات والمخاريط. أدخل القياسات واختر النظام المتري أو الإمبراطوري لتحصل على النتيجة والتحويل فورًا.', calculatorTitle: 'حاسبة تفاعلية', calculateLabel: 'أدخل القياسات', resultLabel: 'الحجم المحسوب', metricLabel: 'متري', imperialLabel: 'إمبراطوري', clearLabel: 'مسح', copyLabel: 'نسخ', guideTitle: 'كيفية حساب الحجم', sections: [{ heading: 'ما هو الحجم؟', paragraphs: ['الحجم هو مقدار الحيز ثلاثي الأبعاد الذي يشغله جسم أو تستوعبه حاوية. من وحداته السنتيمتر المكعب والمتر المكعب واللتر والقدم المكعبة والجالون.', 'لحساب متوازي المستطيلات نستخدم الطول × العرض × الارتفاع. حجم الأسطوانة V = πr²h، وحجم الكرة V = ⁴⁄₃πr³. تتولى الحاسبة تحويل الوحدات تلقائيًا.'] }, { heading: 'اللترات والأمتار المكعبة والخزانات', paragraphs: ['المتر المكعب الواحد يساوي 1,000 لتر بالضبط. لحساب حجم مسبح مستطيل اضرب الطول في العرض في متوسط العمق.', 'استخدم الأبعاد الداخلية لحساب سعة الخزان أو الحاوية، والأبعاد الخارجية لحساب المساحة التي تشغلها الشحنة. يجب قياس جميع الأبعاد بدقة.'] }], faqTitle: 'الأسئلة الشائعة', faqs: [{ question: 'كيف أحسب حجم الأسطوانة؟', answer: 'استخدم القانون V = πr²h، أي مربع نصف القطر مضروبًا في π ثم في الارتفاع.' }, { question: 'كم لترًا في المتر المكعب؟', answer: 'المتر المكعب الواحد يساوي 1,000 لتر بالضبط.' }], shapeNames: { box: 'متوازي المستطيلات', cylinder: 'أسطوانة', sphere: 'كرة', cube: 'مكعب', cone: 'مخروط' },
  },
  hi: {
    code: 'hi', languageName: 'हिन्दी', lang: 'hi', dir: 'ltr', ogLocale: 'hi_IN', title: 'आयतन कैलकुलेटर — लीटर, घन मीटर और गैलन', description: 'सिलेंडर, गोला, घन, शंकु और घनाभ के लिए मुफ्त आयतन कैलकुलेटर। परिणाम लीटर, घन मीटर, घन फुट और गैलन में पाएं।', keywords: 'आयतन कैलकुलेटर, volume calculator, cylinder ka volume calculator, tank volume calculator in liters, घनाभ का आयतन', badge: 'तेज़ और मुफ्त गणना', h1: 'ऑनलाइन आयतन कैलकुलेटर', intro: 'घनाभ, सिलेंडर, गोला, घन और शंकु का आयतन या क्षमता निकालें। माप दर्ज करें, मीट्रिक या इम्पीरियल इकाइयाँ चुनें और तुरंत रूपांतरण प्राप्त करें।', calculatorTitle: 'इंटरैक्टिव कैलकुलेटर', calculateLabel: 'माप दर्ज करें', resultLabel: 'गणना किया गया आयतन', metricLabel: 'मीट्रिक', imperialLabel: 'इम्पीरियल', clearLabel: 'साफ़ करें', copyLabel: 'कॉपी', guideTitle: 'आयतन कैसे निकालें', sections: [{ heading: 'आयतन क्या है?', paragraphs: ['आयतन किसी वस्तु द्वारा घेरे गए त्रि-आयामी स्थान या किसी बर्तन की क्षमता को बताता है। सामान्य इकाइयाँ cm³, m³, लीटर, घन फुट और गैलन हैं।', 'घनाभ के लिए V = लंबाई × चौड़ाई × ऊँचाई, सिलेंडर के लिए V = πr²h और गोले के लिए V = ⁴⁄₃πr³ होता है।'] }, { heading: 'लीटर, घन मीटर और टैंक क्षमता', paragraphs: ['एक घन मीटर ठीक 1,000 लीटर के बराबर होता है। आयताकार पूल का आयतन लंबाई, चौड़ाई और औसत गहराई को गुणा करके निकाला जाता है।', 'टैंक की वास्तविक क्षमता के लिए अंदर के माप लें। शिपिंग या स्टोरेज में जगह जानने के लिए बाहर के माप उपयोग करें।'] }], faqTitle: 'अक्सर पूछे जाने वाले प्रश्न', faqs: [{ question: 'सिलेंडर का आयतन कैसे निकालें?', answer: 'V = πr²h सूत्र लगाएँ: त्रिज्या के वर्ग को π और ऊँचाई से गुणा करें।' }, { question: 'एक घन मीटर में कितने लीटर होते हैं?', answer: 'एक घन मीटर में ठीक 1,000 लीटर होते हैं।' }], shapeNames: { box: 'घनाभ', cylinder: 'सिलेंडर', sphere: 'गोला', cube: 'घन', cone: 'शंकु' },
  },
};

export const LOCALE_CODES = Object.keys(LOCALIZED_HOMES) as LocaleCode[];

export const HOME_ALTERNATES = [
  { hreflang: 'en', href: ENGLISH_HOME },
  ...LOCALE_CODES.map((code) => ({ hreflang: LOCALIZED_HOMES[code].lang, href: `https://thevolumecalculator.com/${code}/` })),
  { hreflang: 'x-default', href: ENGLISH_HOME },
];
